# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "en"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# The output of the plugin can be used below, e.g., {{vars.GithubRepoStarsCountPlugin}}
plugins:
  # Automatically fetch Github repo star count
  - GithubRepoStarsCountPlugin:
      - ZhgChgLi/ZMarkupParser
      - ZhgChgLi/ZReviewTender
      - ZhgChgLi/ZMediumToMarkdown
      - ZhgChgLi/linkyee

# Google Analytics tracking id
google_analytics_id:

# HTML Title
title: "Sami Ennedoui's links"

# Avatar image path
avatar: "https://github.com/sami-ennedoui/links/blob/main/images/sami_ennedoui.jpeg?raw=true"

# Name section text
name: "Sami Ennedoui"

# Tagline section text
tagline: >-
  Élève Ingénieur ModIA | Applied mathematics and AI Engineering student.
# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
links:
  - link:
      icon: "fa-solid fa-rss"
      text: "Website"
      url: "https://sami-ennedoui.github.io"
      alt: "My Portfolio website"
      title: "My Portfolio website"
      target: "_blank"
  - link:
      icon: "fa-solid fa-calendar"
      text: "rythme d'alternance"
      url: "https://github.com/sami-ennedoui/links/blob/main/images/rythme_alternance_ModIA.png?raw=true"
      alt: "Calendrier d'alternance"
      title: "📅 Calendrier d'Alternance (FR)"
      target: "_blank"
  - link:
      icon: "fa-solid fa-graduation-cap"
      text: "Informations sur le parcours ModIA"
      url: "https://www.insa-toulouse.fr/wp-content/uploads/2025/07/Syllabus_ModIA_2025_2026.pdf"
      alt: "Informations sur le parcours ModIA"
      title: "Informations sur le parcours ModIA"
      target: "_blank"
# List of social media links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# title: The url title
# url: The URL of the social media link
# alt: Alternative text for accessibility
# target: _blank opens in a new tab, _self opens in the same frame
socials:
  - social:
      icon: "fa-brands fa-github"
      url: "https://github.com/sami-ennedoui"
      title: "My GitHub"
      alt: "My GitHub"
      target: "_blank"
  - social:
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/sami-ennedoui-1347702a5/"
      title: "My LinkedIn"
      alt: "My LinkedIn"
      target: "_blank"
  - social:
      icon: "fa-solid fa-envelope"
      url: "mailto:samiennedoui@proton.com"
      title: "Email: samienneodui@proton.com"
      alt: "sami-ennedoui@proton.com"
      target: "_blank"

# Footer text
footer: >
    Built by Sami Ennedoui • Hosted on GitHub Pages

# Footer copyright message
# Linkyee is a 100% free, open-source project—feel free to modify the copyright message as you like. :)
copyright: >
  © 2026  <a href="https://sami-ennedoui.github.io" target="_blank">Sami Ennedoui</a>.
